<?php
use AirRobe\TheCircularWardrobe\Block\Order\Success;

try {
    /** @var Success $block */
    $appId = $block->getAppId();
    $orderId = $block->getOrderId();
    $email = $block->getEmail();
} catch (\Throwable $e) {
    $appId = '';
    $orderId = '';
    $email = '';
}
?>
<airrobe-confirmation
  app-id="<?= $appId ?>"
  order-id="<?= $orderId ?>"
  email="<?= $email ?>">
</airrobe-confirmation>
