<airrobe-opt-in
  style="margin-bottom: <?php echo $block->getOptInBottomMargin() ?? 0; ?>; margin-top: <?php echo $block->getOptInTopMargin() ?? 0; ?>"
  app-id="<?php echo $block->getAppId(); ?>"
  category="<?php echo $block->getFirstProductCategory(); ?>"
  price-cents="<?php echo $block->getProductPriceCents(); ?>"
  original-full-price-cents="<?php echo $block->getProductOriginalFullPriceCents(); ?>"
  brand="<?php echo $block->getProductBrand(); ?>"
  material="<?php echo $block->getProductMaterial(); ?>">
</airrobe-opt-in>

