<airrobe-opt-in
  style="margin-bottom: 20px"
  top-margin="<?php echo $block->getOptInTopMargin(); ?>"
  bottom-margin="<?php echo $block->getOptInBottomMargin(); ?>"
  app-id="<?php echo $block->getAppId(); ?>"
  category="<?php echo $block->getFirstProductCategory(); ?>"
  price-cents="<?php echo $block->getProductPriceCents(); ?>"
  original-full-price-cents="<?php echo $block->getProductOriginalFullPriceCents(); ?>"
  brand="<?php echo $block->getProductBrand(); ?>"
  material="<?php echo $block->getProductMaterial(); ?>">
</airrobe-opt-in>

