<?php
//It will call our block which return cookie value
$getCookieData = $block->getCookieData();
?>
<div>

<script type="text/javascript">

document.addEventListener('DOMContentLoaded', function() {
	console.log("Running init code");
	var cookieVal = event.target.checked ? "Yes" : "No";
	document.getElementById('markup').addEventListener('click', function(event) {
		var cookieVal = event.target.checked ? "Yes" : "No";
		console.log("setting cookie to " + cookieVal);
		document.cookie = "airRobeOptedInState=" + cookieVal
	})
});

require(['jquery', 'jquery/ui'], function($){
	jQuery(document).ready( function() {
		function readCookie(name) {
			var cookiename = name + "=";
			var ca = document.cookie.split(';');
			for(var i=0;i < ca.length;i++)
			{
				var c = ca[i];
				while (c.charAt(0)==' ') c = c.substring(1,c.length);
				if (c.indexOf(cookiename) == 0) return c.substring(cookiename.length,c.length);
			}
			return null;
		}
		var is_Set = readCookie('airRobeOptedInState');
		if(is_Set=='Yes')
		{
			document.getElementById("markup").checked = true;
		}
  	});
});
</script>

	<input type="checkbox" name="markup" id="markup" />
	<label for="markup">
		<?php echo "Markup"; ?>
	</label>

</div>
